### PR TITLE
logFaces append via HTTP

### PR DESCRIPTION
**Pull request by sparklton**
logFaces appender is updated with capability to send log events over HTTP for being useful on client side as well. UDP sending is not changed.

### CODE REVIEW

**Comment by nomiddlename** [comment]
Hi, thanks for this - apologies for taking so long to get around to it. A couple of issues - there are no tests that cover the HTTP part, and the HTTP part seems to rely on axios which isn't mentioned anywhere. How will users know they need to install that as well? It also looks like you've changed the format of the UDP messages (different fields).

**Comment by sparklton** [comment]
Hi Gareth, I didn't think there was need to test actual network behavior. Both cases (UDP and HTTP) have network calls stabbed for simplicity. As long as appender works as configured, the test coverage should be sufficient. I think. Am I wrong? I thought that since network dependencies for UDP and HTTP are carried out by modules which have sufficient test coverage, there is no need to test them here. You are right, I should have added some explanation about axios dependency. This appender can be used in server side (node.js) and client side (browserified) where axios was the best choice for doing HTTP calls, we can't do UDP from browsers, this is why HTTP option was added. I will add some "user manual" shortly.

**Comment by nomiddlename** [comment]
You're right - my fault, I misread the test code. Sorry about that.

**Comment by sparklton** [comment]
No problem at all, I've just added some clarifications and links to dependencies.

**Comment by nomiddlename** [comment]
Thanks for this. I'll include it in the 1.1 release (I want to fix #338 before I release that though)

**Comment by nomiddlename** [comment]
Fix pushed to npm in version 1.1.0

**Pull request merged**
