### PR TITLE
add typescript definition

### PR DESCRIPTION
**Pull request by xialeistudio**

### CODE REVIEW

**Comment by nomiddlename** [comment]
Hi, why did you close this PR? I'm happy to see Typescript support added, but I didn't get time to review this properly. Are you planning on submitting another PR? Was there something wrong with this one?

**Comment by xialeistudio** [comment]
sorry,i reopen it

**Comment by nomiddlename** [comment]
Thanks for this. I've pushed the change to NPM in version 2.3.5

**Comment by xialeistudio** [comment]
My Pleasure.

**Pull request merged**
