### PR TITLE
fix: add type defination

### PR DESCRIPTION
**Pull request by taoqf**

### CODE REVIEW

**Comment by taoqf** [comment]
hi @nomiddlename , Could you please checkthis? the travis ci build failed and I don't really this there is problem with my pr.

**Comment by hyq77766177** [comment]
hi, thx for ur contribution, however some properties are still missed in `interface Configuration` such as `pm2` or `categories`.

**Comment by AmShaegar13** [comment]
Ah, damn. I missed this one. Please see !568 for the missing properties in `Configuration`.

**Comment by hyq77766177** [comment]
awesome! hope #568 & #564 can be merged soon :)

**Comment by taoqf** [comment]
is  coming  soon

**Comment by AmShaegar13** [comment]
@taoqf thanks for incorporating my changes. I am still missing `function levels` which is a getter for the levels object and the `levels`property in the `Configuration` interface.

**Comment by taoqf** [comment]
@AmShaegar13 Could you please provide the api or sourcecode? I have not used `levels` property. thanks.

**Comment by taoqf** [comment]
`Levels` is added.

**Comment by AmShaegar13** [comment]
I am not using it either but apperently, you already found it in my PR. ;)

**Comment by taoqf** [comment]
sadly, travis test won't pass now.

**Comment by AmShaegar13** [comment]
Is that really your changes fault? I doubt it. It's only the Node 6 pm2 tests that are failing. I've watched this behaviour in the past. Look at these commits for example:

https://github.com/nomiddlename/log4js-node/commit/5c0f9c9eecd5a564de65500764ce09d4e9b63779 which is the PR introducing index.d.ts
https://github.com/nomiddlename/log4js-node/commit/f965c5454adebe349d66af8040de2e759b698bff which is the merge of that PR

One of them fails, the other doesn't.

**Comment by nomiddlename** [comment]
Thanks for this, really appreciate the effort you've put in. Is it ok to merge this now? Any more changes to come? And does this PR replace #568 or do I need to merge both of them?

**Comment by AmShaegar13** [comment]
#568 is obsolete now.

**Comment by AmShaegar13** [comment]
@nomiddlename testing against my code right now. Got incompatible types. I will get back to you when I know th reasong for it.

**Comment by AmShaegar13** [comment]
I am using a custom appender. I made a PR for @taoqf to add an interface for this.

https://github.com/taoqf/log4js-node/pull/1

**Comment by nomiddlename** [comment]
Travis failure is due to the dodgy pm2 tests, don't worry about that.

**Comment by nomiddlename** [comment]
Let me know if you're happy with this now @taoqf @AmShaegar13

**Comment by AmShaegar13** [comment]
I'm fine with it. My tests are green with the current state of types definition 👍

**Comment by nomiddlename** [comment]
I'm going to merge this now. I'll create a separate issue for automating some tests around this, so that we don't break it again in the future - would be good to get some ideas on how to do that, since I know nothing about typescript.

**Comment by nomiddlename** [comment]
Published to nom in version 2.3.6

**Comment by taoqf** [comment]
thanks @nomiddlename

**Pull request merged**
