### PR TITLE
Implemented shutdown function for SMTP appender

### PR DESCRIPTION
**Pull request by hasegawa-jun**

### CODE REVIEW

**Comment by nomiddlename** [comment]
Thanks for this - I think it would be better to have a timeout, or a limited number of retries, otherwise this can keep the process open forever. For example, try for 5 seconds to send all messages and quit even if unsent messages remain.

**Comment by hasegawa-jun** [comment]
Thank you for your feedback. Please take a look at inserted lines. I just added a timeout option which defaults to 5 seconds.

**Comment by nomiddlename** [comment]
Released in 0.6.23

**Comment by hasegawa-jun** [comment]
Thanks a lot!

**Pull request merged**
