### PR TITLE
Add close-on-SIGHUP behavior for logrotate.

### LINKED ISSUE #343: Close and reopen logs on signal
Systems using `logrotate` need to be able to tell a logging process to close and reopen its logs after it has rotated them, so the process doesn't keep logging to the old inode. Nginx for instance implements this with the -USR1 signal. The file appender in log4js should have a method to close and reopen files, either called from user code or registered as a signal handler.

### PR DESCRIPTION
**Pull request by jsha**
Fixes #343

### CODE REVIEW

**Comment by nomiddlename** [comment]
Thanks for this - I finally got around to merging it and writing a test.

**Comment by jsha** [comment]
Excellent, thanks for the merge (and the test)!

**Comment by nomiddlename** [comment]
Fixed in version 1.0.0

**Comment by GiteshKhanna** [comment]
So which shell command should we be writing in the postrotate of logrotate?

**Comment by nomiddlename** [comment]
You probably want something like `kill -HUP <pid of your app process>`

**Comment by GiteshKhanna** [comment]
> You probably want something like `kill -HUP <pid of your app process>`

So I believe, since I have a java springboot application running slf4j, should I be killing the springboot application? Won't it effect any other services as well?

**Comment by nomiddlename** [comment]
This is an issue about a log library for node.js applications, nothing to do with java, sorry.

**Pull request merged**
