### PR TITLE
Send a remaining logs email when shutdown is called

### PR DESCRIPTION
**Pull request by gchauvet**
Please find attached a patch for log4js SMTP appender that allows to send an email with remaining logs when shutdown method is called. This is useful when we want a one-shot email when a program ending and don't wait the timeout.

Other small changes (out of appender scope) :
- Show process details when vows is launched;
- Ignore other generated temporary files with pattern test/streams/test-*

### CODE REVIEW

**Comment by gchauvet** [comment]
Note: I've not written a unitary test to test the calling of destroy method (I'm weak on vows framework).

**Comment by gchauvet** [comment]
CI failed on something, no issue on UT

**Comment by gchauvet** [comment]
Something wrong in my pull request ?

**Comment by nomiddlename** [comment]
Looks good, thanks for this.

**Comment by nomiddlename** [comment]
Published to npm version 0.6.29

**Pull request merged**
