### PR TITLE
- check if data is available

### PR DESCRIPTION
**Pull request by sentient**
The GELF appender throws an error when data is null. This checks if the data is null.

var test;
logger.info(test);

### CODE REVIEW

**Comment by nomiddlename** [comment]
Could you add a test to cover this, please?

**Comment by sentient** [comment]
ok. I will do that.

I am having some other thoughts as well. It would be nice to have some hooks into the logging framework. e.g. define a hook just before a message is send to the GELF appender (and allowing to define the context object). This very specific to GELF, but I had something similar with the File Appender. 

Have you considered hooks for customization? Or are there other mechanisme you would suggest before a message is send to a particular appender.

**Comment by sentient** [comment]
@nomiddlename Do you have some documentation how I run the existing test framework?
Do you use grunt or gulp to kickstart this? 
I'm not familiar with .bob.json

**Comment by sentient** [comment]
I think I got it
```
 > npm install bob -g

> npm install

 > bob test

> bob lint

....

```

**Comment by nomiddlename** [comment]
If you just want to run the tests, "npm test" will do fine. Don't worry about the lint part.

**Comment by sentient** [comment]
There was an issue that the 'should be compressed' is failing. I don't think that is related to the code change. Do all your test run fine at the moment?

**Comment by nomiddlename** [comment]
This is a fix for issue #173 - I will look into this now that version 2 is out.

**Comment by nomiddlename** [comment]
Thanks for the PR, I used your idea to fix the issue - but I couldn't merge the PR due to all the changes that have happened in version 2.x.

**Pull request closed without merging**
