### PR TITLE
Synchronous dateFile appender (With modes)

### PR DESCRIPTION
**Pull request by Smurf-IV**
Add new "thin" wrapper over DateRollingAppender, to allow 2 flavours of synchronous writing, 1 is (the default) via fsyncSync, the other via fsync via a config entry of `usefsync: true`.
Addition of unit tests based off of existing Date appender testing.

### CODE REVIEW

**Comment by Smurf-IV** [comment]
This is not my test, so my code should still go in ?
test/streams/rollingFileStream-test.js
Does the fs emulation have to also include the fsyncSync methods ?

**Comment by Smurf-IV** [comment]
Why is node 4.x LTS and Node 5.x not tested via **travis-cli** ?

**Comment by Smurf-IV** [comment]
build 419.3 against 1345504 has this error:
`npm ERR! weird error 1` for the mailgun console write.
This build system does not inspire confidence !
Anyway, Please accept the changes.

**Comment by Smurf-IV** [comment]
[Created an explanation page here:](https://github.com/nomiddlename/log4js-node/wiki/Date-rolling-file-appender---with-synchronous-file-output-modes)

**Comment by nomiddlename** [comment]
I'm a bit confused as to the purpose of this. Calling `fsync` after every write sounds expensive. I would have thought a synchronous appender would just use `writeSync`. Perhaps it's a naming problem - this seems to be more of a "guaranteed write" appender than a synchronous appender, since all the file operations are still asynchronous. 

If you agree, then this functionality should be moved into BaseRollingFileStream (with a "fsyncAfterWrite" option), so that it can then be used by both rolling file streams, not just the date file roller. What do you think?

**Comment by nomiddlename** [comment]
(Oh, and yes - I agree that I should update the travis config to use some more up-to-date node versions, thanks for reminding me)

**Comment by Smurf-IV** [comment]
fsyncSync is the default, and yes it would be "partially blocking", all Sync calls in Node are "expensive", but still hand-off to the underlying OS to perform the write whilst "they" just wait for the call to return.

Adding into the base class would not allow for the "2 types" of sync call to be selected without an "Enum / text" check requirement. (Not impossible just not as simple)

Also if moving to the base class then the FileSync should also be refactored to be a base class override.

Thoughts ?

**Comment by nomiddlename** [comment]
Closing this because there have been a lot of changes to the file appenders since this was first proposed.

**Comment by emouawad** [comment]
Any updates on this? Has this been merged yet? if not @Smurf-IV  do you have a working Lib?

**Pull request closed without merging**
