### PR TITLE
Remove the underscore dependency

### PR DESCRIPTION
**Pull request by hmalphettes**
Hi, I noticed that `package.json` was referring to `underscore` twice.
Given that there are only 2 places where it is used, I ventured into removing it all together.
I hope this helps.
Thanks for your attention!

### CODE REVIEW

**Comment by nomiddlename** [comment]
Cool - these changes make the code a little easier to read. I thought underscore was used in more places, but I guess not. Thanks for this.

**Comment by hmalphettes** [comment]
Cheers!

I don't really have an agenda but if you you find it interesting to look at, I can give a shot at removing the handful of `async.series`, `async.each`, `async.eachSeries`, `async.whilst` with some recursive code.

**Comment by nomiddlename** [comment]
If you've got the time, feel free. As long as it makes the code easier to understand, that's great - but I don't want to have to add too much complexity for the sake of removing a dependency.

**Comment by shinnn** [comment]
@nomiddlename Can you publish a new version that include this change?

**Comment by nomiddlename** [comment]
Pushed to npm in version 0.6.30

**Comment by shinnn** [comment]
@nomiddlename Thanks!

**Pull request merged**
